{% set name = "janitor-rs" %}
{% set version = "0.6.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 54d4f4103a484b1e9c070214a4da2adaee781f02ed30a3895ccf6ef4e9ed2c76

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  skip: true  # [py<38]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - pip
    - python
    - maturin >=1.9,<2.0
  run:
    - python

test:
  imports:
    - janitor_rs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyjanitor-devs/janitor-rs
  summary: Improve perf for pyjanitor functions with Rust
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  license_family: MIT
  description: Improve perf for pyjanitor functions with Rust
  doc_url: https://github.com/pyjanitor-devs/janitor-rs
  dev_url: https://github.com/pyjanitor-devs/janitor-rs


extra:
  recipe-maintainers:
    - ericmjl
